obj-y += spi_nand.o
spi_nand-objs := drvSPINAND_hal.o \
                 drvSPINAND.o \
                 drvSPINAND_api.o \
                 spinand.o

#obj-y += spinand.o
#obj-y += drvSPINAND_hal.o
#obj-y += drvSPINAND.o



ccflags-y += -I$(srctree)/$(src)/inc/common
ccflags-y += -I$(srctree)/$(src)/inc/config
ccflags-y += -I$(srctree)/$(src)/inc
