obj-y += drvNAND.o
obj-y += src/api/drvNAND_prg.o
obj-y += src/common/drvNAND_hal.o
obj-y += src/common/drvNAND_hal_v5.o
obj-y += src/common/drvNAND_ReadRetry_v5.o
obj-y += src/common/drvNAND_utl.o
obj-y += src/common/drvNAND_ip_verify.o
obj-y += src/config/drvNAND_platform.o


ccflags-y += -I$(srctree)/$(src)/inc/api
ccflags-y += -I$(srctree)/$(src)/inc/common
ccflags-y += -I$(srctree)/$(src)/inc/config
